service:
  name: flux-build

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: build.gitNotify
    events:
      - sns: flux-app-build-notify-git
